### ISSUE TITLE
App Does Not Compile

### ISSUE THREAD

**Issue by commonsguy** [googlesamples/android-SharingShortcuts#2]
Steps to Reproduce:

- Clone the repo
- Attempt to build the app

Expected Results: for the app to build

Actual Results: the app fails with compile errors on references to `Intent.EXTRA_SHORTCUT_ID`, as [that is new to Android Q](https://developer.android.com/reference/android/content/Intent?hl=en#EXTRA_SHORTCUT_ID) but the `Application` module's `compileSdkVersion` is 28

Workaround: change `Application/build.gradle` to use `compileSdkVersion 'android-Q'`

**Comment by romellfudi** [comment]
i have the same problem

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
